// Intent: API route that calls the AI model and normalizes test questions.
import { NextResponse } from 'next/server'

/**Helper Function: extractJsonObjects
 * finds first and last curly braces and parses the inside substring as json text.
 * this is used because sometimes the model returns extra text before or after json. This function
 * strips said  extra text so parsing doesn't fail. 
*/
function extractJsonObject(text) {
  const firstBrace = text.indexOf('{')
  const lastBrace = text.lastIndexOf('}')
  if (firstBrace === -1 || lastBrace === -1 || lastBrace <= firstBrace) {
    throw new Error('No JSON object found in model response.')
  }
  return JSON.parse(text.slice(firstBrace, lastBrace + 1))
}
/*Helper function: normalizeQuestions.
 * takes whatever is generated by the model and makes it consistent 
 * with user requests in terms of questions count, type, and difficulty.
*/
function normalizeQuestions(rawQuestions, questionCount) {
  return rawQuestions.slice(0, questionCount).map((question, index) => ({
    id: question.id || `q-${index + 1}`,
    type: question.type || 'Short-answer',
    prompt: question.prompt || 'Generated question',
    choices: Array.isArray(question.choices) ? question.choices.filter(Boolean) : undefined,
    difficulty: question.difficulty || 'Medium',
    source: question.source || 'Uploaded material',
  }))
}

export async function POST(request) {
  try {
    const apiKey = process.env.OPENAI_API_KEY
    if (!apiKey) {
      return NextResponse.json(
        { error: 'Missing OPENAI_API_KEY in server environment.' },
        { status: 500 }
      )
    }

    const {
      title,
      questionCount,
      questionTypes,
      difficultyDistribution,
      sourceText,
    } = await request.json()

    const count = Number(questionCount)
    if (!title || !Number.isInteger(count) || count < 1 || count > 100) {
      return NextResponse.json(
        { error: 'Invalid input: title and question count (1-100) are required.' },
        { status: 400 }
      )
    }

    const selectedTypes = Object.entries(questionTypes || {})
      .filter(([, enabled]) => Boolean(enabled))
      .map(([key]) => key)

    if (selectedTypes.length === 0) {
      return NextResponse.json(
        { error: 'Select at least one question type.' },
        { status: 400 }
      )
    }

    const model = process.env.OPENAI_MODEL || 'gpt-4.1-mini'
    const prompt = `
Generate ${count} test questions.
Title: ${title}
Allowed types: ${selectedTypes.join(', ')}
Difficulty distribution: ${difficultyDistribution || 'Even'}
Source text:
${sourceText || 'No source text provided.'}

Return strict JSON with this shape:
{
  "questions": [
    {
      "id": "q-1",
      "type": "Multiple-choice|Short-answer|True/False",
      "prompt": "question text",
      "choices": ["A", "B", "C", "D"], // include only when type is Multiple-choice
      "difficulty": "Easy|Medium|Hard",
      "source": "short source reference"
    }
  ]
}
`

    const aiResponse = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model,
        temperature: 0.3,
        response_format: { type: 'json_object' },
        messages: [
          {
            role: 'system',
            content: 'You create classroom-ready test questions and must return valid JSON only.',
          },
          {
            role: 'user',
            content: prompt,
          },
        ],
      }),
    })

    if (!aiResponse.ok) {
      const errorPayload = await aiResponse.text()
      return NextResponse.json(
        { error: `AI request failed: ${errorPayload}` },
        { status: 502 }
      )
    }

    const completion = await aiResponse.json()
    const content = completion?.choices?.[0]?.message?.content || '{}'
    const parsed = extractJsonObject(content)
    const rawQuestions = Array.isArray(parsed.questions) ? parsed.questions : []
    const questions = normalizeQuestions(rawQuestions, count)

    return NextResponse.json({ questions })
  } catch (error) {
    return NextResponse.json(
      { error: `Unexpected server error: ${error.message}` },
      { status: 500 }
    )
  }
}
